# Docker Compose configuration for AI Story Generator Frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount for development with hot reload
      # - ./src:/app/src:ro
      # - ./public:/app/public:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network
    restart: unless-stopped

  # Optional: Add backend service if you have one
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app-network
  #   restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  nginx-logs: 